logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.openqa.selenium: WARN
    life.freebao.devops: INFO

application:
  webdriver:
    baidu:
      search.url: https://www.baidu.com
      search.cron: 1 1 1 1 1 ? #remove line to disable task
    router:
      login.url: http://192.168.1.253
      login.username: admin
      login.password: admin
      login.cron: 0 30 * * * ?
      status.url: http://192.168.1.253
      status.cron: 15 15 15 * * ?
      information.url: http://192.168.1.253
      information.text.cron: 45 45 * * * ?
      information.image.cron: 5 5 9 * * ?
      reboot.url: http://192.168.1.253
      reboot.normal.cron: 30 5 5 ? * 6
      reboot.abnormal.cron: 15 * * * * ?
    screenshot.path: /srv/packages/router
    browser:
      name: chrome
      options: --no-sandbox,--disable-gpu #--headless
    timeout: 30
  wecom:
    router.token: 9d44e914-27d2-6161-1c46-79767ef6379c
